number = 5
slug = "subobjects-classification"
status = "completed"
description = "Attempt CT074-CT077 subobjects, subobject classifier, characteristic morphism..."
role = "production"
context_files = []
created_at = "2026-08-14T15:30:55"
completed_at = "2026-08-14T17:15:25"
task_type = "lesson"
commits = ["929ef9ea497c2fb9f5251ded0d8becd1acf95111"]
