number = 5
slug = "subobjects-classification"
status = "in-progress"
description = "Attempt CT074-CT077 subobjects, subobject classifier, characteristic morphism..."
role = "production"
context_files = []
created_at = "2026-08-14T15:30:55"
task_type = "lesson"
commits = []
